// Mapping from our crypto codes to CoinGecko IDs
export const COINGECKO_IDS: Record<string, string> = {
  BTC: "bitcoin", ETH: "ethereum", USDT: "tether", BNB: "binancecoin",
  XRP: "ripple", ADA: "cardano", DOGE: "dogecoin", SOL: "solana",
  TRX: "tron", DOT: "polkadot", MATIC: "matic-network", LTC: "litecoin",
  SHIB: "shiba-inu", AVAX: "avalanche-2", UNI: "uniswap", LINK: "chainlink",
  ATOM: "cosmos", XMR: "monero", ETC: "ethereum-classic", BCH: "bitcoin-cash",
  XLM: "stellar", ALGO: "algorand", FIL: "filecoin", VET: "vechain",
  ICP: "internet-computer", APT: "aptos", HBAR: "hedera-hashgraph",
  NEAR: "near", QNT: "quant-network", ARB: "arbitrum", OP: "optimism",
  GRT: "the-graph", MKR: "maker", AAVE: "aave", STX: "blockstack",
  EGLD: "elrond-erd-2", SAND: "the-sandbox", MANA: "decentraland",
  AXS: "axie-infinity", THETA: "theta-token", FTM: "fantom", XTZ: "tezos",
  EOS: "eos", KLAY: "klay-token", FLOW: "flow", CHZ: "chiliz",
  ENJ: "enjincoin", ZEC: "zcash", DASH: "dash", NEO: "neo",
  IOTA: "iota", CAKE: "pancakeswap-token", "1INCH": "1inch",
  BAT: "basic-attention-token", ZIL: "zilliqa", HOT: "holotoken",
  ICX: "icon", OMG: "omisego", COMP: "compound-governance-token",
  SNX: "havven", YFI: "yearn-finance", CRV: "curve-dao-token",
  SUSHI: "sushi", BAL: "balancer", REN: "republic-protocol",
  UMA: "uma", LRC: "loopring", QTUM: "qtum", WAVES: "waves",
  ONT: "ontology", ZRX: "0x", CELO: "celo", KAVA: "kava",
  RSR: "reserve-rights-token", ANKR: "ankr", SKL: "skale",
  STORJ: "storj", BAND: "band-protocol", OCEAN: "ocean-protocol",
  NMR: "numeraire", KNC: "kyber-network-crystal", REP: "augur",
  RVN: "ravencoin", DCR: "decred", SC: "siacoin", DGB: "digibyte",
  XEM: "nem", LSK: "lisk", STEEM: "steem", DENT: "dent",
  WTC: "waltonchain", ARDR: "ardor", STRAT: "stratis", BTS: "bitshares",
  SYS: "syscoin", POWR: "power-ledger", GNT: "golem",
};
