// Crypto list for chart dropdown (extracted from CryptoChart)
export const CRYPTO_LIST = [
  { code: "BTC", name: "Bitcoin" }, { code: "ETH", name: "Ethereum" },
  { code: "USDT", name: "Tether" }, { code: "BNB", name: "Binance Coin" },
  { code: "XRP", name: "Ripple" }, { code: "ADA", name: "Cardano" },
  { code: "SOL", name: "Solana" }, { code: "DOGE", name: "Dogecoin" },
  { code: "MATIC", name: "Polygon" }, { code: "DOT", name: "Polkadot" },
  { code: "SHIB", name: "Shiba Inu" }, { code: "TRX", name: "Tron" },
  { code: "AVAX", name: "Avalanche" }, { code: "LINK", name: "Chainlink" },
  { code: "UNI", name: "Uniswap" }, { code: "ATOM", name: "Cosmos" },
  { code: "LTC", name: "Litecoin" }, { code: "XLM", name: "Stellar" },
  { code: "BCH", name: "Bitcoin Cash" }, { code: "ALGO", name: "Algorand" },
  { code: "VET", name: "VeChain" }, { code: "FIL", name: "Filecoin" },
  { code: "ICP", name: "Internet Computer" }, { code: "APT", name: "Aptos" },
  { code: "HBAR", name: "Hedera" }, { code: "NEAR", name: "NEAR Protocol" },
  { code: "QNT", name: "Quant" }, { code: "ARB", name: "Arbitrum" },
  { code: "OP", name: "Optimism" }, { code: "GRT", name: "The Graph" },
  { code: "MKR", name: "Maker" }, { code: "AAVE", name: "Aave" },
  { code: "STX", name: "Stacks" }, { code: "EGLD", name: "MultiversX" },
  { code: "SAND", name: "The Sandbox" }, { code: "MANA", name: "Decentraland" },
  { code: "AXS", name: "Axie Infinity" }, { code: "THETA", name: "Theta Network" },
  { code: "FTM", name: "Fantom" }, { code: "XTZ", name: "Tezos" },
  { code: "EOS", name: "EOS" }, { code: "KLAY", name: "Klaytn" },
  { code: "FLOW", name: "Flow" }, { code: "CHZ", name: "Chiliz" },
  { code: "ENJ", name: "Enjin Coin" }, { code: "ZEC", name: "Zcash" },
  { code: "DASH", name: "Dash" }, { code: "NEO", name: "Neo" },
  { code: "IOTA", name: "IOTA" }, { code: "CAKE", name: "PancakeSwap" },
  { code: "1INCH", name: "1inch" }, { code: "BAT", name: "Basic Attention Token" },
  { code: "ZIL", name: "Zilliqa" }, { code: "HOT", name: "Holo" },
  { code: "ICX", name: "ICON" }, { code: "OMG", name: "OMG Network" },
  { code: "COMP", name: "Compound" }, { code: "SNX", name: "Synthetix" },
  { code: "YFI", name: "yearn.finance" }, { code: "CRV", name: "Curve DAO Token" },
  { code: "SUSHI", name: "SushiSwap" }, { code: "BAL", name: "Balancer" },
  { code: "REN", name: "Ren" }, { code: "UMA", name: "UMA" },
  { code: "LRC", name: "Loopring" }, { code: "QTUM", name: "Qtum" },
  { code: "WAVES", name: "Waves" }, { code: "ONT", name: "Ontology" },
  { code: "ZRX", name: "0x" }, { code: "CELO", name: "Celo" },
  { code: "KAVA", name: "Kava" }, { code: "RSR", name: "Reserve Rights" },
  { code: "ANKR", name: "Ankr" }, { code: "SKL", name: "SKALE Network" },
  { code: "STORJ", name: "Storj" }, { code: "BAND", name: "Band Protocol" },
  { code: "OCEAN", name: "Ocean Protocol" }, { code: "NMR", name: "Numeraire" },
  { code: "KNC", name: "Kyber Network" }, { code: "REP", name: "Augur" },
  { code: "RVN", name: "Ravencoin" }, { code: "DCR", name: "Decred" },
  { code: "SC", name: "Siacoin" }, { code: "DGB", name: "DigiByte" },
  { code: "XEM", name: "NEM" }, { code: "LSK", name: "Lisk" },
  { code: "STEEM", name: "Steem" }, { code: "DENT", name: "Dent" },
  { code: "WTC", name: "Waltonchain" }, { code: "ARDR", name: "Ardor" },
  { code: "STRAT", name: "Stratis" }, { code: "BTS", name: "BitShares" },
  { code: "SYS", name: "Syscoin" }, { code: "POWR", name: "Power Ledger" },
  { code: "GNT", name: "Golem" },
];
