import { Currency } from "@/types";

export const CURRENCIES: Currency[] = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
  { code: "CLP", name: "Chilean Peso", symbol: "$" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا" },
  { code: "LBP", name: "Lebanese Pound", symbol: "£" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م." },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "Rs" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "so'm" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "ЅМ" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "m" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د" },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин." },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден" },
  { code: "ALL", name: "Albanian Lek", symbol: "L" },
  { code: "BAM", name: "Bosnia-Herzegovina Mark", symbol: "KM" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK" },
  { code: "BWP", name: "Botswanan Pula", symbol: "P" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨" },
  { code: "NAD", name: "Namibian Dollar", symbol: "$" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK" },
  { code: "RWF", name: "Rwandan Franc", symbol: "Fr" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "Fr" },
  { code: "XOF", name: "West African CFA Franc", symbol: "Fr" },
  { code: "COP", name: "Colombian Peso", symbol: "$" },
  { code: "VEF", name: "Venezuelan Bolívar", symbol: "Bs." },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs." },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
  { code: "BTC", name: "Bitcoin", symbol: "₿" },
  { code: "ETH", name: "Ethereum", symbol: "Ξ" },
  { code: "USDT", name: "Tether", symbol: "₮" },
  { code: "BNB", name: "Binance Coin", symbol: "BNB" },
  { code: "XRP", name: "Ripple", symbol: "XRP" },
  { code: "ADA", name: "Cardano", symbol: "₳" },
  { code: "DOGE", name: "Dogecoin", symbol: "Ð" },
  { code: "SOL", name: "Solana", symbol: "◎" },
  { code: "TRX", name: "Tron", symbol: "TRX" },
  { code: "DOT", name: "Polkadot", symbol: "DOT" },
  { code: "MATIC", name: "Polygon", symbol: "MATIC" },
  { code: "LTC", name: "Litecoin", symbol: "Ł" },
  { code: "SHIB", name: "Shiba Inu", symbol: "SHIB" },
  { code: "AVAX", name: "Avalanche", symbol: "AVAX" },
  { code: "UNI", name: "Uniswap", symbol: "UNI" },
  { code: "LINK", name: "Chainlink", symbol: "LINK" },
  { code: "ATOM", name: "Cosmos", symbol: "ATOM" },
  { code: "XMR", name: "Monero", symbol: "XMR" },
  { code: "ETC", name: "Ethereum Classic", symbol: "ETC" },
  { code: "BCH", name: "Bitcoin Cash", symbol: "BCH" },
  { code: "XLM", name: "Stellar", symbol: "XLM" },
  { code: "ALGO", name: "Algorand", symbol: "ALGO" },
  { code: "FIL", name: "Filecoin", symbol: "FIL" },
  { code: "VET", name: "VeChain", symbol: "VET" },
  { code: "ICP", name: "Internet Computer", symbol: "ICP" },
  { code: "APT", name: "Aptos", symbol: "APT" },
  { code: "HBAR", name: "Hedera", symbol: "HBAR" },
  { code: "NEAR", name: "NEAR Protocol", symbol: "NEAR" },
  { code: "QNT", name: "Quant", symbol: "QNT" },
  { code: "ARB", name: "Arbitrum", symbol: "ARB" },
  { code: "OP", name: "Optimism", symbol: "OP" },
  { code: "GRT", name: "The Graph", symbol: "GRT" },
  { code: "MKR", name: "Maker", symbol: "MKR" },
  { code: "AAVE", name: "Aave", symbol: "AAVE" },
  { code: "STX", name: "Stacks", symbol: "STX" },
  { code: "EGLD", name: "MultiversX", symbol: "EGLD" },
  { code: "SAND", name: "The Sandbox", symbol: "SAND" },
  { code: "MANA", name: "Decentraland", symbol: "MANA" },
  { code: "AXS", name: "Axie Infinity", symbol: "AXS" },
  { code: "THETA", name: "Theta Network", symbol: "THETA" },
  { code: "FTM", name: "Fantom", symbol: "FTM" },
  { code: "XTZ", name: "Tezos", symbol: "XTZ" },
  { code: "EOS", name: "EOS", symbol: "EOS" },
  { code: "KLAY", name: "Klaytn", symbol: "KLAY" },
  { code: "FLOW", name: "Flow", symbol: "FLOW" },
  { code: "CHZ", name: "Chiliz", symbol: "CHZ" },
  { code: "ENJ", name: "Enjin Coin", symbol: "ENJ" },
  { code: "ZEC", name: "Zcash", symbol: "ZEC" },
  { code: "DASH", name: "Dash", symbol: "DASH" },
  { code: "NEO", name: "Neo", symbol: "NEO" },
  { code: "IOTA", name: "IOTA", symbol: "IOTA" },
  { code: "CAKE", name: "PancakeSwap", symbol: "CAKE" },
  { code: "1INCH", name: "1inch", symbol: "1INCH" },
  { code: "BAT", name: "Basic Attention Token", symbol: "BAT" },
  { code: "ZIL", name: "Zilliqa", symbol: "ZIL" },
  { code: "HOT", name: "Holo", symbol: "HOT" },
  { code: "ICX", name: "ICON", symbol: "ICX" },
  { code: "OMG", name: "OMG Network", symbol: "OMG" },
  { code: "COMP", name: "Compound", symbol: "COMP" },
  { code: "SNX", name: "Synthetix", symbol: "SNX" },
  { code: "YFI", name: "yearn.finance", symbol: "YFI" },
  { code: "CRV", name: "Curve DAO Token", symbol: "CRV" },
  { code: "SUSHI", name: "SushiSwap", symbol: "SUSHI" },
  { code: "BAL", name: "Balancer", symbol: "BAL" },
  { code: "REN", name: "Ren", symbol: "REN" },
  { code: "UMA", name: "UMA", symbol: "UMA" },
  { code: "LRC", name: "Loopring", symbol: "LRC" },
  { code: "QTUM", name: "Qtum", symbol: "QTUM" },
  { code: "WAVES", name: "Waves", symbol: "WAVES" },
  { code: "ONT", name: "Ontology", symbol: "ONT" },
  { code: "ZRX", name: "0x", symbol: "ZRX" },
  { code: "CELO", name: "Celo", symbol: "CELO" },
  { code: "KAVA", name: "Kava", symbol: "KAVA" },
  { code: "RSR", name: "Reserve Rights", symbol: "RSR" },
  { code: "ANKR", name: "Ankr", symbol: "ANKR" },
  { code: "SKL", name: "SKALE Network", symbol: "SKL" },
  { code: "STORJ", name: "Storj", symbol: "STORJ" },
  { code: "BAND", name: "Band Protocol", symbol: "BAND" },
  { code: "OCEAN", name: "Ocean Protocol", symbol: "OCEAN" },
  { code: "NMR", name: "Numeraire", symbol: "NMR" },
  { code: "KNC", name: "Kyber Network", symbol: "KNC" },
  { code: "REP", name: "Augur", symbol: "REP" },
  { code: "RVN", name: "Ravencoin", symbol: "RVN" },
  { code: "DCR", name: "Decred", symbol: "DCR" },
  { code: "SC", name: "Siacoin", symbol: "SC" },
  { code: "DGB", name: "DigiByte", symbol: "DGB" },
  { code: "XEM", name: "NEM", symbol: "XEM" },
  { code: "LSK", name: "Lisk", symbol: "LSK" },
  { code: "STEEM", name: "Steem", symbol: "STEEM" },
  { code: "DENT", name: "Dent", symbol: "DENT" },
  { code: "WTC", name: "Waltonchain", symbol: "WTC" },
  { code: "ARDR", name: "Ardor", symbol: "ARDR" },
  { code: "STRAT", name: "Stratis", symbol: "STRAT" },
  { code: "BTS", name: "BitShares", symbol: "BTS" },
  { code: "SYS", name: "Syscoin", symbol: "SYS" },
  { code: "POWR", name: "Power Ledger", symbol: "POWR" },
  { code: "GNT", name: "Golem", symbol: "GNT" },
];

export const EXCHANGE_RATES: Record<string, number> = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 149.5,
  AUD: 1.52,
  CAD: 1.36,
  CHF: 0.88,
  CNY: 7.24,
  INR: 83.12,
  MXN: 17.05,
  BRL: 4.98,
  ZAR: 18.65,
  RUB: 92.5,
  KRW: 1315.8,
  SGD: 1.34,
  HKD: 7.83,
  NOK: 10.87,
  SEK: 10.45,
  DKK: 6.87,
  NZD: 1.63,
  TRY: 28.75,
  PLN: 4.02,
  THB: 35.12,
  IDR: 15678.5,
  HUF: 356.8,
  CZK: 22.45,
  ILS: 3.65,
  CLP: 892.5,
  PHP: 55.87,
  AED: 3.67,
  SAR: 3.75,
  MYR: 4.68,
  RON: 4.56,
  ARS: 350.25,
  VND: 24385.0,
  BGN: 1.8,
  HRK: 6.92,
  PEN: 3.72,
  UAH: 36.85,
  EGP: 30.95,
  QAR: 3.64,
  KWD: 0.31,
  OMR: 0.38,
  BHD: 0.38,
  JOD: 0.71,
  LBP: 15000.0,
  MAD: 10.12,
  TND: 3.12,
  DZD: 135.6,
  PKR: 278.5,
  BDT: 110.25,
  LKR: 325.8,
  MMK: 2098.5,
  NPR: 133.0,
  KZT: 458.9,
  UZS: 12345.0,
  GEL: 2.68,
  AMD: 398.5,
  AZN: 1.7,
  BYN: 3.27,
  KGS: 88.65,
  TJS: 10.95,
  TMT: 3.5,
  IQD: 1310.0,
  IRR: 42000.0,
  AFN: 70.8,
  ISK: 138.2,
  RSD: 108.5,
  MKD: 56.8,
  ALL: 96.5,
  BAM: 1.8,
  MDL: 17.85,
  KES: 157.2,
  GHS: 12.15,
  NGN: 765.8,
  TZS: 2505.0,
  UGX: 3725.0,
  ZMW: 26.85,
  BWP: 13.65,
  MUR: 45.8,
  NAD: 18.65,
  SCR: 13.25,
  ETB: 112.5,
  AOA: 825.0,
  MZN: 63.75,
  MWK: 1025.0,
  RWF: 1235.0,
  XAF: 605.0,
  XOF: 605.0,
  COP: 3925.0,
  VEF: 3562500.0,
  UYU: 39.25,
  PYG: 7325.0,
  BOB: 6.92,
  CRC: 528.5,
  GTQ: 7.82,
  HNL: 24.68,
  NIO: 36.72,
  PAB: 1.0,
  BTC: 0.000023,
  ETH: 0.00031,
  USDT: 1.0,
  BNB: 0.0021,
  XRP: 1.85,
  ADA: 2.15,
  DOGE: 11.2,
  SOL: 0.0095,
  TRX: 9.85,
  DOT: 0.14,
  MATIC: 1.28,
  LTC: 0.014,
  SHIB: 92500,
  AVAX: 0.028,
  UNI: 0.18,
  LINK: 0.071,
  ATOM: 0.095,
  XMR: 0.0068,
  ETC: 0.045,
  BCH: 0.0045,
  XLM: 8.25,
  ALGO: 6.85,
  FIL: 0.21,
  VET: 42.5,
  ICP: 0.095,
  APT: 0.12,
  HBAR: 18.5,
  NEAR: 0.52,
  QNT: 0.011,
  ARB: 1.32,
  OP: 0.62,
  GRT: 6.95,
  MKR: 0.00042,
  AAVE: 0.0115,
  STX: 1.85,
  EGLD: 0.022,
  SAND: 2.58,
  MANA: 2.32,
  AXS: 0.18,
  THETA: 1.12,
  FTM: 2.85,
  XTZ: 1.28,
  EOS: 1.52,
  KLAY: 6.85,
  FLOW: 1.35,
  CHZ: 11.5,
  ENJ: 4.25,
  ZEC: 0.035,
  DASH: 0.038,
  NEO: 0.092,
  IOTA: 6.25,
  CAKE: 0.42,
  "1INCH": 2.85,
  BAT: 4.68,
  ZIL: 42.5,
  HOT: 385.0,
  ICX: 6.85,
  OMG: 1.32,
  COMP: 0.022,
  SNX: 0.42,
  YFI: 0.00015,
  CRV: 1.85,
  SUSHI: 1.28,
  BAL: 0.21,
  REN: 12.5,
  UMA: 0.42,
  LRC: 4.85,
  QTUM: 0.42,
  WAVES: 0.52,
  ONT: 6.25,
  ZRX: 3.85,
  CELO: 2.15,
  KAVA: 1.85,
  RSR: 185.0,
  ANKR: 38.5,
  SKL: 28.5,
  STORJ: 2.85,
  BAND: 1.25,
  OCEAN: 2.65,
  NMR: 0.068,
  KNC: 1.85,
  REP: 0.082,
  RVN: 45.5,
  DCR: 0.072,
  SC: 285.0,
  DGB: 125.0,
  XEM: 28.5,
  LSK: 1.32,
  STEEM: 4.85,
  DENT: 1250.0,
  WTC: 2.85,
  ARDR: 12.5,
  STRAT: 18.5,
  BTS: 285.0,
  SYS: 12.5,
  POWR: 4.25,
  GNT: 6.85,
};
